name: ai_virtual_girlfriend
description: A Flutter AI Virtual Girlfriend IM application.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  flutter_chat_ui: ^1.6.6
  flutter_chat_types: ^3.6.0
  uuid: ^3.0.7
  intl: ^0.18.0
  image_picker: ^0.8.7+4
  path_provider: ^2.0.14
  flutter_dotenv: ^5.0.2
  flutter_tts: ^3.6.3
  speech_to_text: ^6.1.1
  video_player: ^2.7.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env